server:
  port: 8080

spring:
  application:
    name: B40-API
  datasource:
    username: 'backend-pinelabs'
    url: jdbc:postgresql://localhost:5432/B40-API
    password: 'muaz_hansom'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
