server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never


spring:
  application:
    name: B40-API
  datasource:
    username: 'backend-pinelabs'
    #username: acfvfkwwzakwkx
    url: jdbc:postgresql://localhost:5432/B40-API
    #url: jdbc:postgresql://ec2-52-207-15-147.compute-1.amazonaws.com
    password: 'muaz_hansom'
    #password: 8c6e74c211aab80af689b31bd1986438948db50d6ad3812e987d0f1cd6178fea
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /api/swagger
