server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never


spring:
  application:
    name: B40-API
  datasource:
    #username: 'backend-pinelabs'
    username: nmmkjproxgdikb
    url: jdbc:postgresql://localhost:5432/B40-API
    #url: jdbc:postgresql://ec2-52-207-15-147.compute-1.amazonaws.com
    #password: 'muaz_hansom'
    password: 9e836215075276325f8a0b61cf406717e11763c63607a5d40c177bd4abe7c554
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /api/swagger
